### ISSUE TITLE
Can you help with this error?

### ISSUE THREAD

**Issue by hardword** [pownjs/pown#1]
$ pown
/usr/local/lib/node_modules/pown/node_modules/pown-cli/index.js:8
    let y = yargs.usage(`Usage: $0 [options] <command> [command options]`)
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/pown/index.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

I'm using
OSX El Captain

$ node -v
v4.4.7

$ npm -v
4.2.0

**Comment by jesusprubio** [comment]
Hi, please try with a more recent Node version (v6-7) :)

**Comment by hardword** [comment]
Thanks!
I used to use homebrew to install node and got the version I mentioned.
I reinstall node with official package and it works charm.
Thanks again
